// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtfuO_M2Ypvj2go-EOPp3Ed0HryfHzJw',
    appId: '1:520548208973:android:eb68ff5969434f5fce2704',
    messagingSenderId: '520548208973',
    projectId: 'cancer-20de5',
    storageBucket: 'cancer-20de5.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcm74U9k6acE6MzvZSi3zvpFMAJDNFIrA',
    appId: '1:520548208973:web:92ef4e413ee79bcfce2704',
    messagingSenderId: '520548208973',
    projectId: 'cancer-20de5',
    authDomain: 'cancer-20de5.firebaseapp.com',
    storageBucket: 'cancer-20de5.appspot.com',
    measurementId: 'G-WH2RF30Y8X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTLyYCWULKONvGxJ-Y7LtbatN-qyfUXo',
    appId: '1:520548208973:ios:93af95f39c444437ce2704',
    messagingSenderId: '520548208973',
    projectId: 'cancer-20de5',
    storageBucket: 'cancer-20de5.appspot.com',
    iosBundleId: 'com.example.cancer',
  );

}